import { GoogleGenerativeAI } from '@google/generative-ai';

// Lazy initialization of Gemini client
let genAI = null;
let model = null;

const getGeminiModel = () => {
  if (!genAI) {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  }
  return model;
};

/**
 * Generate a summary from a transcript using Gemini
 * @param {string} transcript - The full transcript text
 * @returns {Promise<string>} - The generated summary
 */
export const generateSummary = async (transcript) => {
  if (!transcript || transcript.length < 50) {
    return 'Transcript too short to summarize. Please provide more content.';
  }

  const prompt = `You are an expert at summarizing audio recordings and meetings. 
Please analyze the following transcript and provide a clear, concise summary.

IMPORTANT: Only include sections that have actual content from the transcript. If something wasn't discussed or mentioned, DO NOT include that section at all. Never write things like "No decisions were made" or "Not mentioned" - simply omit that section entirely.

Include ONLY if present in the transcript:
- Main topics discussed
- Key points and takeaways
- Decisions made (only if actual decisions were made)
- Important information mentioned

Format the summary with clear sections using markdown.

Transcript:
"""
${transcript}
"""

Please provide a well-structured summary (only including sections with actual content):`;

  try {
    console.log('Generating summary with Gemini...');
    const result = await getGeminiModel().generateContent(prompt);
    const response = await result.response;
    const summary = response.text();
    console.log('Summary generated successfully');
    return summary;
  } catch (error) {
    console.error('Gemini summary error:', error);
    throw new Error(`Failed to generate summary: ${error.message}`);
  }
};

/**
 * Generate meeting minutes from a transcript using Gemini
 * @param {string} transcript - The full transcript text
 * @param {string} summary - Optional existing summary
 * @param {string} title - The meeting/recording title
 * @returns {Promise<string>} - The generated meeting minutes
 */
export const generateMeetingMinutes = async (transcript, summary, title) => {
  if (!transcript || transcript.length < 50) {
    return 'Transcript too short to generate minutes. Please provide more content.';
  }

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const prompt = `You are an expert at creating professional meeting minutes. 
Please analyze the following transcript and generate comprehensive meeting minutes.

Meeting Title: ${title || 'Untitled Meeting'}
Date: ${date}

${summary ? `Existing Summary:\n${summary}\n` : ''}

Transcript:
"""
${transcript}
"""

IMPORTANT RULES:
1. ONLY include sections that have actual content from the transcript
2. If something wasn't discussed or mentioned, DO NOT include that section at all
3. Never write "No decisions were made", "None mentioned", "Not specified", "N/A" etc. - simply OMIT the entire section
4. Only include attendees/speakers if actual names were mentioned
5. Only include action items if specific tasks were discussed
6. Only include decisions if actual decisions were reached
7. Only include next steps if they were explicitly mentioned

Create professional meeting minutes in markdown format. Start with:

# Meeting Minutes

**Meeting:** ${title || 'Untitled Meeting'}
**Date:** ${date}

---

Then ONLY include these sections if they have actual content:
- Attendees/Speakers (only if names mentioned)
- Topics Discussed (main subjects covered)
- Key Discussion Points (important details)
- Decisions Made (only if decisions were actually made)
- Action Items (only if specific tasks mentioned)
- Next Steps (only if follow-ups discussed)

End with:
---
*Minutes generated by RecAI* (dont mention gemini )  ` ;

  try {
    console.log('Generating meeting minutes with Gemini...');
    const result = await getGeminiModel().generateContent(prompt);
    const response = await result.response;
    const minutes = response.text();
    console.log('Meeting minutes generated successfully');
    return minutes;
  } catch (error) {
    console.error('Gemini minutes error:', error);
    throw new Error(`Failed to generate meeting minutes: ${error.message}`);
  }
};

/**
 * Generate action items from a transcript
 * @param {string} transcript - The full transcript text
 * @returns {Promise<Array>} - Array of action items
 */
export const extractActionItems = async (transcript) => {
  if (!transcript || transcript.length < 50) {
    return [];
  }

  const prompt = `Analyze the following transcript and extract any action items, tasks, or to-dos mentioned.

Transcript:
"""
${transcript}
"""

Return the action items as a JSON array with objects containing:
- "task": the action item description
- "assignee": who should do it (or "Unassigned" if not mentioned)
- "priority": "high", "medium", or "low" based on context
- "deadline": any mentioned deadline (or null if not mentioned)

Return ONLY the JSON array, no other text.`;

  try {
    console.log('Extracting action items with Gemini...');
    const result = await getGeminiModel().generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    // Parse JSON from response
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
    return [];
  } catch (error) {
    console.error('Gemini action items error:', error);
    return [];
  }
};

export default { generateSummary, generateMeetingMinutes, extractActionItems };
